prerelease: patch version
swerik-project/riksdagen-persons pull request #32
Opened 2024-12-13 13:08 UTC by BobBorges

prepare release: since changes concern workflows, tests and documentation, but not data, it goes as a patch version

2024-12-13 13:17 UTC, MansMeg commented
Sounds reasonable.

2025-01-08 17:16 UTC, MansMeg requested changes
Hi! I found some minor issues that probably should be fixed (version numbers in plots).

2025-01-08 17:16 UTC, MansMeg commented on quality/estimates/mp-coverage/mp-coverage.png
The version seem incorrect?

2025-01-08 17:16 UTC, MansMeg commented on .github/workflows/prerelease.yml
I cant really judge the workflows. Ill see how it works.

2025-01-08 17:16 UTC, MansMeg commented on docs/index.html
This is hard to review I think. But maybe easer later on when we have more proper diffs.

2025-01-08 17:16 UTC, MansMeg commented on quality/docs/qe_mp-coverage.md
> +## The code
?

2025-01-08 17:16 UTC, MansMeg commented on quality/estimates/mp-coverage/mp-coverage-ratio.png
No version 1.1.1?

2025-01-10 13:03 UTC, ninpnin approved these changes
LGTM

2025-01-10 14:01 UTC, BobBorges commented on docs/index.html
There is no need for diffs here -- this is automatically generated by pdoc

2025-01-10 14:03 UTC, BobBorges commented on quality/docs/qe_mp-coverage.md
> +## The code
What's the question?

2025-01-10 14:10 UTC, BobBorges commented on quality/estimates/mp-coverage/mp-coverage-ratio.png
I see what the problem is and know how to fix it, but it will happen early next week.

2025-01-10 14:15 UTC, BobBorges commented on quality/docs/qe_mp-coverage.md
> +## The code
Not in the markdown file, but the pdoc run adds all the code to the docs folder -- this readme file is like a template for the compiled documentation.

Look here: https://github.com/swerik-project/riksdagen-motions/blob/main/test/docs/general-integrity-tests.md

then here: https://swerik-project.github.io/riksdagen-motions/riksdagen-motions/test/integrity.html

When we merge this into main, we'll get the same type of documentation about the riksdagen-persons repo tests under swerik-project.github.io.

2025-01-10 14:33 UTC, MansMeg commented on quality/docs/qe_mp-coverage.md
> +## The code
Ah! Nice!

2025-01-10 14:34 UTC, MansMeg commented on docs/index.html
Ah! Great!

2025-01-13 16:16 UTC, ninpnin approved these changes

2025-01-13 16:18 UTC, ninpnin commented on quality/estimates/mp-coverage/mp-coverage.png
Now it says v99.99.99

2025-01-14 07:42 UTC, BobBorges commented on quality/estimates/mp-coverage/mp-coverage.png
I see that -- it's b/c the workflow failed and the plots with correct version nr were not committed. 

v99.99.99 is there so that when we open PR to **dev** the plots get generated and we can see what effect the commits have. It's v99.99.99 so that it gets sorted on top, and obviously is not the current released version. With PR to **main**, the plots are written with the about-to-be-released version. 

...hang in there it will all work soon :D

2025-01-14 09:57 UTC, MansMeg approved these changes

2025-01-14 09:58 UTC, MansMeg commented
Great!

2025-01-15 10:59 UTC, merged